title: tastebud.studio the food & flavor adventures blog!
description: tastebud.studio is the blog where Joel records the food & flavor adventures he has with his taste buddies. 
author: Joel Taylor
copyright: ©️2023-2025 

remote_theme: "mmistakes/minimal-mistakes@4.27.3"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache